{ 
"boo":true,
"able":true,
"openads":"", 
"banner":"ca-app-pub-8841289226244835/3009292828", 
"reward":"", 
"title":"Updated Version 1.8.1 ",
"main":"https://apkguidemm.net/lee/", 
"about":"ယခု ဗားရှင်းမှာ အမျိုးအစားအလိုက် ဇာတ်ကားတွ ကြည့်ရှူ့နိုင်ဖို့ ထပ်မံ ဖြည့်တိုးထားပါတယ်
(ဇာတ်ကား အသစ်တွေနဲ့အတူ ဗားရှင်းအသစ်ထွက်နေပြီ ဂေါင်းကြီးတို့😍 အခုပဲ ဆော့လ်ဝဲကို အဆင့်မြှင့်တင်လိုက်ပါ)",
"update":"com.apyar.ffourmovies", 
"version":1, 
"adtype":"open ca-app-pub-8841289226244835/4775183526 banner ca-app-pub-8841289226244835/3009292828 rew ca-app-pub-8841289226244835/9688453061 inter ca-app-pub-8841289226244835/8714428539 ",
"interstial":"ca-app-pub-8841289226244835/8714428539" }
